#25 Implement additional Package/NamingRule
devonfw-sample/archunit pull request #27
Opened 2023-02-28 12:26 UTC by moritzLanger

2023-02-28 16:15 UTC, hohwille requested changes
@moritzLanger thanks for your PR. Great job, you have implemented the new rules well 👍 
Still I have some review comments to align new with existing rules to make this more readable and have all requirements in one place. Also I found some small things to improve. Please have a look at my review comments.

2023-02-28 16:15 UTC, hohwille commented on src/test/java/com/devonfw/sample/archunit/NamingConventionTest.java
> +                   .because("Classes extending ApplicationPersistenceEntity must be located in the package dataaccess");
I would merge this together with the existing Entity rule `N3DevonNamingConventionEntityCheck`.

2023-02-28 16:15 UTC, hohwille commented on src/test/java/com/devonfw/sample/archunit/NamingConventionTest.java
> +                   });
I would merge this with the existing ETO rule in lines 42-51.

2023-02-28 16:15 UTC, hohwille commented on src/test/java/com/devonfw/sample/archunit/NamingConventionTest.java
> +                  .should().resideInAnyPackage("..dataaccess..")
`.andShould().haveSimpleNameEndingWith("Repository")`

2023-02-28 16:15 UTC, hohwille commented on src/test/java/com/devonfw/sample/archunit/NamingConventionTest.java
> +                   .because("Classes extending Mapper must be located in the package logic and end with Mapper");
replace `Classes extending Mapper` with `Bean-Mappers` or `Types annotated with @Mapper` as our mappers are interfaces and not classes and they do not extend `Mapper` but are annotated with it.

2023-02-28 16:15 UTC, hohwille commented on src/test/java/com/devonfw/sample/archunit/NamingConventionTest.java
> +                   .because("Classes extending Path must be located in the package service and end with Service");
replace `Classes extending Path` with `Rest-services` or `Types annotated with @Path`.

2023-02-28 16:15 UTC, hohwille commented on src/test/java/com/devonfw/sample/archunit/NamingConventionTest.java
> +                   });
I would merge this with the existing ETO rule `N4DevonNamingConventionEtoCheck`.

2023-02-28 16:15 UTC, hohwille commented on src/test/java/com/devonfw/sample/archunit/NamingConventionTest.java
> +                   .that().areAssignableTo(AbstractUc.class).should().resideInAnyPackage("..logic..")
`.andShould().haveSimpleNameStartingWith("Uc")`

ATTENTION: We do have some base-usecases starting with `AbstractUc` so either we add this with OR conjunction or even better we distinguish abstract from non-abstract classes here.

2023-02-28 16:15 UTC, hohwille commented on src/test/java/com/devonfw/sample/archunit/NamingConventionTest.java
> +            classes()
does `classes()` cover all types or just classes?
Please note that our mappers and repositories (see line 131) are interfaces.

2023-03-01 09:32 UTC, moritzLanger commented on src/test/java/com/devonfw/sample/archunit/NamingConventionTest.java
> +            classes()
Yes in Archunit Interfaces are included in the methods classes() and noclasses().

2023-03-13 19:09 UTC, hohwille approved these changes
@moritzLanger Thanks for your rework and all the improvements addressing my review comments. 👍 

We still have two rules for `AbstractUc` spread across the test, but I will simply merge and this can still be improved once there is some time left.

2023-03-13 19:09 UTC, merged